# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PredictR_view\subsystem_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subsystem(object):
    def setupUi(self, Subsystem):
        Subsystem.setObjectName("Subsystem")
        Subsystem.resize(863, 867)
        self.verticalLayout = QtWidgets.QVBoxLayout(Subsystem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Subsystem)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cwpblDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.cwpblDoubleSpinBox.setSingleStep(0.25)
        self.cwpblDoubleSpinBox.setProperty("value", 0.5)
        self.cwpblDoubleSpinBox.setObjectName("cwpblDoubleSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cwpblDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cwpbsDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.cwpbsDoubleSpinBox.setMinimum(0.01)
        self.cwpbsDoubleSpinBox.setMaximum(200.0)
        self.cwpbsDoubleSpinBox.setSingleStep(0.1)
        self.cwpbsDoubleSpinBox.setProperty("value", 1.0)
        self.cwpbsDoubleSpinBox.setObjectName("cwpbsDoubleSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cwpbsDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cwpbnSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.cwpbnSpinBox.setMinimum(1)
        self.cwpbnSpinBox.setMaximum(200)
        self.cwpbnSpinBox.setProperty("value", 30)
        self.cwpbnSpinBox.setObjectName("cwpbnSpinBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cwpbnSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cwpbbDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.cwpbbDoubleSpinBox.setDecimals(3)
        self.cwpbbDoubleSpinBox.setSingleStep(0.05)
        self.cwpbbDoubleSpinBox.setProperty("value", 0.5)
        self.cwpbbDoubleSpinBox.setObjectName("cwpbbDoubleSpinBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cwpbbDoubleSpinBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cwpbbComboBox = QtWidgets.QComboBox(self.groupBox)
        self.cwpbbComboBox.setObjectName("cwpbbComboBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cwpbbComboBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cwppSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.cwppSpinBox.setMaximum(500)
        self.cwppSpinBox.setProperty("value", 1)
        self.cwppSpinBox.setObjectName("cwppSpinBox")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cwppSpinBox)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cwptbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.cwptbpDoubleSpinBox.setSingleStep(0.1)
        self.cwptbpDoubleSpinBox.setProperty("value", 0.1)
        self.cwptbpDoubleSpinBox.setObjectName("cwptbpDoubleSpinBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cwptbpDoubleSpinBox)
        self.cwponCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.cwponCheckBox.setText("")
        self.cwponCheckBox.setObjectName("cwponCheckBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cwponCheckBox)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.recommendSettingGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.recommendSettingGroupBox.setObjectName("recommendSettingGroupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.recommendSettingGroupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.recommendCfgComboBox = QtWidgets.QComboBox(self.recommendSettingGroupBox)
        self.recommendCfgComboBox.setObjectName("recommendCfgComboBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.recommendCfgComboBox)
        self.presetButton = QtWidgets.QPushButton(self.recommendSettingGroupBox)
        self.presetButton.setObjectName("presetButton")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.presetButton)
        self.verticalLayout_6.addWidget(self.recommendSettingGroupBox)
        self.numBeamsGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.numBeamsGroupBox.setObjectName("numBeamsGroupBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.numBeamsGroupBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_15 = QtWidgets.QLabel(self.numBeamsGroupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.numBeamsSpinBox = QtWidgets.QSpinBox(self.numBeamsGroupBox)
        self.numBeamsSpinBox.setMinimum(1)
        self.numBeamsSpinBox.setMaximum(4)
        self.numBeamsSpinBox.setProperty("value", 4)
        self.numBeamsSpinBox.setObjectName("numBeamsSpinBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numBeamsSpinBox)
        self.label_28 = QtWidgets.QLabel(self.numBeamsGroupBox)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.beamDiaComboBox = QtWidgets.QComboBox(self.numBeamsGroupBox)
        self.beamDiaComboBox.setObjectName("beamDiaComboBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.beamDiaComboBox)
        self.label_30 = QtWidgets.QLabel(self.numBeamsGroupBox)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.beamAngleComboBox = QtWidgets.QComboBox(self.numBeamsGroupBox)
        self.beamAngleComboBox.setObjectName("beamAngleComboBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beamAngleComboBox)
        self.verticalLayout_6.addWidget(self.numBeamsGroupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cbtonCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbtonCheckBox.setText("")
        self.cbtonCheckBox.setObjectName("cbtonCheckBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbtonCheckBox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cbtbbComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.cbtbbComboBox.setObjectName("cbtbbComboBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbtbbComboBox)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cbttbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.cbttbpDoubleSpinBox.setObjectName("cbttbpDoubleSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbttbpDoubleSpinBox)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cbiBurstIntervalDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.cbiBurstIntervalDoubleSpinBox.setMinimum(0.0)
        self.cbiBurstIntervalDoubleSpinBox.setMaximum(86400.0)
        self.cbiBurstIntervalDoubleSpinBox.setProperty("value", 3600.0)
        self.cbiBurstIntervalDoubleSpinBox.setObjectName("cbiBurstIntervalDoubleSpinBox")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbiBurstIntervalDoubleSpinBox)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cbiNumEnsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.cbiNumEnsSpinBox.setMaximum(5000)
        self.cbiNumEnsSpinBox.setSingleStep(128)
        self.cbiNumEnsSpinBox.setProperty("value", 1024)
        self.cbiNumEnsSpinBox.setObjectName("cbiNumEnsSpinBox")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbiNumEnsSpinBox)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.cbiInterleaveCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbiInterleaveCheckBox.setText("")
        self.cbiInterleaveCheckBox.setObjectName("cbiInterleaveCheckBox")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbiInterleaveCheckBox)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cbiEnabledCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbiEnabledCheckBox.setText("")
        self.cbiEnabledCheckBox.setObjectName("cbiEnabledCheckBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbiEnabledCheckBox)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_11 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_7.setObjectName("formLayout_7")
        self.rangeTrackingComboBox = QtWidgets.QComboBox(self.groupBox_11)
        self.rangeTrackingComboBox.setObjectName("rangeTrackingComboBox")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rangeTrackingComboBox)
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        self.label_22.setObjectName("label_22")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.cwprtRangeFractionSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.cwprtRangeFractionSpinBox.setProperty("value", 0.5)
        self.cwprtRangeFractionSpinBox.setObjectName("cwprtRangeFractionSpinBox")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cwprtRangeFractionSpinBox)
        self.label_24 = QtWidgets.QLabel(self.groupBox_11)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.cwprtMinBinSpinBox = QtWidgets.QSpinBox(self.groupBox_11)
        self.cwprtMinBinSpinBox.setObjectName("cwprtMinBinSpinBox")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cwprtMinBinSpinBox)
        self.label_26 = QtWidgets.QLabel(self.groupBox_11)
        self.label_26.setObjectName("label_26")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.cwprtMaxBinSpinBox = QtWidgets.QSpinBox(self.groupBox_11)
        self.cwprtMaxBinSpinBox.setObjectName("cwprtMaxBinSpinBox")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cwprtMaxBinSpinBox)
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        self.label_20.setObjectName("label_20")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_3.addWidget(self.groupBox_11)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.cedGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.cedGroupBox.setObjectName("cedGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.cedGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cedBeamVelCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedBeamVelCheckBox.setObjectName("cedBeamVelCheckBox")
        self.gridLayout_4.addWidget(self.cedBeamVelCheckBox, 0, 0, 1, 1)
        self.cedCorrCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedCorrCheckBox.setObjectName("cedCorrCheckBox")
        self.gridLayout_4.addWidget(self.cedCorrCheckBox, 0, 1, 1, 1)
        self.cedAncCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedAncCheckBox.setObjectName("cedAncCheckBox")
        self.gridLayout_4.addWidget(self.cedAncCheckBox, 0, 2, 1, 1)
        self.cedBtEngCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedBtEngCheckBox.setObjectName("cedBtEngCheckBox")
        self.gridLayout_4.addWidget(self.cedBtEngCheckBox, 0, 3, 1, 1)
        self.cedInstrVelCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedInstrVelCheckBox.setObjectName("cedInstrVelCheckBox")
        self.gridLayout_4.addWidget(self.cedInstrVelCheckBox, 1, 0, 1, 1)
        self.cedBeamGoodPingCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedBeamGoodPingCheckBox.setObjectName("cedBeamGoodPingCheckBox")
        self.gridLayout_4.addWidget(self.cedBeamGoodPingCheckBox, 1, 1, 1, 1)
        self.cedBtCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedBtCheckBox.setObjectName("cedBtCheckBox")
        self.gridLayout_4.addWidget(self.cedBtCheckBox, 1, 2, 1, 1)
        self.cedSysSettingCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedSysSettingCheckBox.setObjectName("cedSysSettingCheckBox")
        self.gridLayout_4.addWidget(self.cedSysSettingCheckBox, 1, 3, 1, 1)
        self.cedEarthVelCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedEarthVelCheckBox.setObjectName("cedEarthVelCheckBox")
        self.gridLayout_4.addWidget(self.cedEarthVelCheckBox, 2, 0, 1, 1)
        self.cedEarthGoodPingCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedEarthGoodPingCheckBox.setObjectName("cedEarthGoodPingCheckBox")
        self.gridLayout_4.addWidget(self.cedEarthGoodPingCheckBox, 2, 1, 1, 1)
        self.cedNmeaCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedNmeaCheckBox.setObjectName("cedNmeaCheckBox")
        self.gridLayout_4.addWidget(self.cedNmeaCheckBox, 2, 2, 1, 1)
        self.cedRangeTrackingCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedRangeTrackingCheckBox.setObjectName("cedRangeTrackingCheckBox")
        self.gridLayout_4.addWidget(self.cedRangeTrackingCheckBox, 2, 3, 1, 1)
        self.cedAmpCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedAmpCheckBox.setObjectName("cedAmpCheckBox")
        self.gridLayout_4.addWidget(self.cedAmpCheckBox, 3, 0, 1, 1)
        self.cedEnsCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedEnsCheckBox.setObjectName("cedEnsCheckBox")
        self.gridLayout_4.addWidget(self.cedEnsCheckBox, 3, 1, 1, 1)
        self.cedWpEngCheckBox = QtWidgets.QCheckBox(self.cedGroupBox)
        self.cedWpEngCheckBox.setObjectName("cedWpEngCheckBox")
        self.gridLayout_4.addWidget(self.cedWpEngCheckBox, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.cedGroupBox)
        self.predictionGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.predictionGroupBox.setAutoFillBackground(False)
        self.predictionGroupBox.setObjectName("predictionGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.predictionGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.powerDataGroupBox = QtWidgets.QGroupBox(self.predictionGroupBox)
        self.powerDataGroupBox.setObjectName("powerDataGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.powerDataGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.powerDataGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.powerDataGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 0, 1, 1)
        self.dataUsageLabel = QtWidgets.QLabel(self.powerDataGroupBox)
        self.dataUsageLabel.setText("")
        self.dataUsageLabel.setObjectName("dataUsageLabel")
        self.gridLayout_5.addWidget(self.dataUsageLabel, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.powerDataGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.powerLabel = QtWidgets.QLabel(self.powerDataGroupBox)
        self.powerLabel.setText("")
        self.powerLabel.setObjectName("powerLabel")
        self.gridLayout_5.addWidget(self.powerLabel, 0, 1, 1, 1)
        self.numBatteriesLabel = QtWidgets.QLabel(self.powerDataGroupBox)
        self.numBatteriesLabel.setText("")
        self.numBatteriesLabel.setObjectName("numBatteriesLabel")
        self.gridLayout_5.addWidget(self.numBatteriesLabel, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.powerDataGroupBox)
        self.rangeGroupBox = QtWidgets.QGroupBox(self.predictionGroupBox)
        self.rangeGroupBox.setObjectName("rangeGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.rangeGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.firstBinPosLabel = QtWidgets.QLabel(self.rangeGroupBox)
        self.firstBinPosLabel.setText("")
        self.firstBinPosLabel.setObjectName("firstBinPosLabel")
        self.gridLayout_2.addWidget(self.firstBinPosLabel, 0, 1, 1, 1)
        self.wpRangeLabel = QtWidgets.QLabel(self.rangeGroupBox)
        self.wpRangeLabel.setText("")
        self.wpRangeLabel.setObjectName("wpRangeLabel")
        self.gridLayout_2.addWidget(self.wpRangeLabel, 1, 1, 1, 1)
        self.btRangeLabel = QtWidgets.QLabel(self.rangeGroupBox)
        self.btRangeLabel.setText("")
        self.btRangeLabel.setObjectName("btRangeLabel")
        self.gridLayout_2.addWidget(self.btRangeLabel, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.rangeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.rangeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.rangeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 2, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.rangeGroupBox)
        self.velAccGroupBox = QtWidgets.QGroupBox(self.predictionGroupBox)
        self.velAccGroupBox.setObjectName("velAccGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.velAccGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtWidgets.QLabel(self.velAccGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.stdLabel = QtWidgets.QLabel(self.velAccGroupBox)
        self.stdLabel.setText("")
        self.stdLabel.setObjectName("stdLabel")
        self.gridLayout_3.addWidget(self.stdLabel, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.velAccGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.maxVelLabel = QtWidgets.QLabel(self.velAccGroupBox)
        self.maxVelLabel.setText("")
        self.maxVelLabel.setObjectName("maxVelLabel")
        self.gridLayout_3.addWidget(self.maxVelLabel, 0, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.velAccGroupBox)
        self.verticalLayout.addWidget(self.predictionGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.statusGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pingingTextBrowser = QtWidgets.QTextBrowser(self.statusGroupBox)
        self.pingingTextBrowser.setObjectName("pingingTextBrowser")
        self.verticalLayout_3.addWidget(self.pingingTextBrowser)
        self.horizontalLayout.addWidget(self.statusGroupBox)
        self.errorGroupBox = QtWidgets.QGroupBox(Subsystem)
        self.errorGroupBox.setObjectName("errorGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.errorGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.errorTextBrowser = QtWidgets.QTextBrowser(self.errorGroupBox)
        self.errorTextBrowser.setObjectName("errorTextBrowser")
        self.verticalLayout_2.addWidget(self.errorTextBrowser)
        self.horizontalLayout.addWidget(self.errorGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Subsystem)
        QtCore.QMetaObject.connectSlotsByName(Subsystem)

    def retranslateUi(self, Subsystem):
        _translate = QtCore.QCoreApplication.translate
        Subsystem.setWindowTitle(_translate("Subsystem", "MainWindow"))
        self.groupBox.setTitle(_translate("Subsystem", "Water Profile"))
        self.label.setText(_translate("Subsystem", "CWPON"))
        self.label_2.setText(_translate("Subsystem", "CWPBL (m)"))
        self.label_3.setText(_translate("Subsystem", "CWPBS (m)"))
        self.label_4.setText(_translate("Subsystem", "CWPBN (bins)"))
        self.label_5.setText(_translate("Subsystem", "CWPBB Lag Length (m)"))
        self.label_6.setText(_translate("Subsystem", "Pulse Type"))
        self.label_7.setText(_translate("Subsystem", "CWPP (pings)"))
        self.label_8.setText(_translate("Subsystem", "CWPTBP (s)"))
        self.recommendSettingGroupBox.setTitle(_translate("Subsystem", "Recommend Setting"))
        self.presetButton.setText(_translate("Subsystem", "LOAD"))
        self.numBeamsGroupBox.setTitle(_translate("Subsystem", "Beams"))
        self.label_15.setText(_translate("Subsystem", "Number of Beams"))
        self.label_28.setText(_translate("Subsystem", "Beam Diameter"))
        self.label_30.setText(_translate("Subsystem", "Beam Angle"))
        self.groupBox_2.setTitle(_translate("Subsystem", "Bottom Track"))
        self.label_9.setText(_translate("Subsystem", "CBTON"))
        self.label_10.setText(_translate("Subsystem", "CBTBB"))
        self.label_11.setText(_translate("Subsystem", "CBTTBP (s)"))
        self.groupBox_3.setTitle(_translate("Subsystem", "Burst Mode"))
        self.label_13.setText(_translate("Subsystem", "Burst Interval (s)"))
        self.label_14.setText(_translate("Subsystem", "Number of Ensembles"))
        self.label_18.setText(_translate("Subsystem", "Interleave"))
        self.label_12.setText(_translate("Subsystem", "Burst Mode ON"))
        self.groupBox_11.setTitle(_translate("Subsystem", "Range Tracking"))
        self.label_22.setText(_translate("Subsystem", "Range Fraction"))
        self.label_24.setText(_translate("Subsystem", "Minimum Bin"))
        self.label_26.setText(_translate("Subsystem", "Maximum Bin"))
        self.label_20.setText(_translate("Subsystem", "Range Tracking"))
        self.cedGroupBox.setTitle(_translate("Subsystem", "Data Output"))
        self.cedBeamVelCheckBox.setText(_translate("Subsystem", "Beam Vel"))
        self.cedCorrCheckBox.setText(_translate("Subsystem", "Correlation"))
        self.cedAncCheckBox.setText(_translate("Subsystem", "Ancillary"))
        self.cedBtEngCheckBox.setText(_translate("Subsystem", "BT Engineering"))
        self.cedInstrVelCheckBox.setText(_translate("Subsystem", "Instrument Vel"))
        self.cedBeamGoodPingCheckBox.setText(_translate("Subsystem", "Beam Good Ping"))
        self.cedBtCheckBox.setText(_translate("Subsystem", "Bottom Track"))
        self.cedSysSettingCheckBox.setText(_translate("Subsystem", "System Settings"))
        self.cedEarthVelCheckBox.setText(_translate("Subsystem", "Earth Vel"))
        self.cedEarthGoodPingCheckBox.setText(_translate("Subsystem", "Earth Good Ping"))
        self.cedNmeaCheckBox.setText(_translate("Subsystem", "NMEA"))
        self.cedRangeTrackingCheckBox.setText(_translate("Subsystem", "Range Tracking"))
        self.cedAmpCheckBox.setText(_translate("Subsystem", "Amplitude"))
        self.cedEnsCheckBox.setText(_translate("Subsystem", "Ensemble"))
        self.cedWpEngCheckBox.setText(_translate("Subsystem", "WP Engineering"))
        self.predictionGroupBox.setTitle(_translate("Subsystem", "Predictions"))
        self.powerDataGroupBox.setTitle(_translate("Subsystem", "Power and Data"))
        self.label_17.setText(_translate("Subsystem", "Num Batteries: "))
        self.label_29.setText(_translate("Subsystem", "Data Usage: "))
        self.label_16.setText(_translate("Subsystem", "Power Usage: "))
        self.rangeGroupBox.setTitle(_translate("Subsystem", "Maximum Range"))
        self.label_23.setText(_translate("Subsystem", "First Bin Position: "))
        self.label_25.setText(_translate("Subsystem", "Water Profile Range: "))
        self.label_27.setText(_translate("Subsystem", "Bottom Track Range: "))
        self.velAccGroupBox.setTitle(_translate("Subsystem", "Velocity and Accuracy"))
        self.label_19.setText(_translate("Subsystem", "Maximum Velocity: "))
        self.label_21.setText(_translate("Subsystem", "Standard Deviation: "))
        self.statusGroupBox.setTitle(_translate("Subsystem", "Status"))
        self.errorGroupBox.setTitle(_translate("Subsystem", "Errors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subsystem = QtWidgets.QWidget()
    ui = Ui_Subsystem()
    ui.setupUi(Subsystem)
    Subsystem.show()
    sys.exit(app.exec_())
